language: go

go:
  - 1.x

dist: xenial

addons:
  apt:
    packages:
    - cmake
    - gcc

before_install:
  - wget http://download.osgeo.org/geos/geos-3.7.1.tar.bz2
  - tar xvfj geos-3.7.1.tar.bz2
  - pushd geos-3.7.1 && mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig && popd
  - sudo apt-get install -y liblwgeom-2.5-0 liblwgeom-dev

script: 
  - go test -covermode=atomic -coverprofile=coverage.txt -v ./geos/...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - srimaln91@gmail.com
