language: go

go:
  - 1.1

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt update
  - sudo apt install -q libgeos-dev libgeos-3.7.0

script: go test -v ./...
notifications:
  email:
    - srimaln91@gmail.com